# Generated by Django 4.0.5 on 2022-07-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('mach_id', models.IntegerField()),
                ('punch_in', models.DateTimeField(blank=True, null=True)),
                ('punch_out', models.DateTimeField(blank=True, null=True)),
                ('active', models.IntegerField(default=0)),
                ('time', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
