# Generated by Django 4.0.5 on 2022-07-18 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch_backend', '0003_alter_employee_start_date_alter_job_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 17, 21, 9, 14, 241450)),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 17, 21, 9, 14, 240450)),
        ),
    ]
