# Generated by Django 4.0.5 on 2022-07-18 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch_backend', '0004_alter_employee_in_time_alter_employee_out_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_in',
            field=models.BooleanField(blank=True, null=True, verbose_name=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 17, 21, 10, 46, 933508)),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 17, 21, 10, 46, 932507)),
        ),
    ]
