# Generated by Django 4.0.5 on 2022-07-18 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch_backend', '0006_alter_employee_is_in_alter_employee_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 17, 21, 38, 5, 481049)),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 17, 21, 38, 5, 480048)),
        ),
    ]
