# Generated by Django 4.0.5 on 2023-05-31 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch_backend', '0012_alter_employee_start_date_alter_job_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 30, 22, 57, 45, 320267)),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 30, 22, 57, 45, 319266)),
        ),
    ]
