# Generated by Django 4.0.5 on 2023-08-07 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch_backend', '0013_alter_employee_start_date_alter_job_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockevent',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='clockevent',
            name='job',
        ),
        migrations.RemoveField(
            model_name='clockevent',
            name='machine',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_number',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='machine_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AddField(
            model_name='machine',
            name='mach_id',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='coverage_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='drivers_license',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_in',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 22, 11, 52, 385188)),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 22, 11, 52, 385188)),
        ),
        migrations.AlterField(
            model_name='timepunch',
            name='emp_id',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='timepunch',
            name='job_id',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='timepunch',
            name='mach_id',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.DeleteModel(
            name='ClockEvent',
        ),
    ]
